# Default values for fft_boxing.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

jobParam:
  name: []
  description: []
  restartPolicy: OnFailure

cfl: 
  ntrials: 1 
  seed: 202207 
  rounds: 20 
  num_users: 10 
  frac: 0.5 
  local_ep: 10 
  local_bs: 10 
  lr: 0.001 
  momentum: 0.9 
  glob_momentum: 0.0 
  model: 'simple-cnn' 
  dataset: 'cifar10' 
  partition: 'homo' 
  partition_difficulty_dist: 'rand' 
  num_partitions: 100 
  ordering: 'rand' 
  pacing_f: 'step' 
  pacing_a: 1.0 
  pacing_b: 1.0 
  client_ordering: 'rand' 
  client_pacing_f: 'step' 
  client_pacing_a: 1.0 
  client_pacing_b: 1.0 
  client_bs: 10 
  exp_label: 'Default' 
  datadir: 'data/' 
  logdir: 'save_results/' 
  ptdir: 'pretrain/' 
  train_expert: 'False' 
  log_clientnet: 'False' 
  data_score_sample_p: 0.01 
  client_score_sample_n: 1 
  log_filename: 'client100_rand_step_1.0a_1.0b_data_rand_step_1.0a_1.0b_gloss_p100' 
  alg: 'fedavg_curr_lg_loss' 
  beta: 0.1 
  local_view: True  
  lg_scoring: 'G' 
  noise: 0 
  gpu: 0 
  print_freq: 10
  
credentialSecret: []
code:
  server: lambda-alpha.ucsd.edu
  directory: ~/Projects/Curriculum-FL

storage:
  data: cfl-dataset-pvc
  results: cfl-result-pvc
  pretain: cfl-pretrain-pvc

image:
  registry: lambda-alpha.ucsd.edu

resources:
  limits:
    cpu: 6000m
    memory: 20Gi
    nvidia.com/gpu: 1
  requests:
    cpu: 4000m
    memory: 16Gi
    nvidia.com/gpu: 1

requiredGPU: []
# requiredGPU: 
# - NVIDIA-GeForce-GTX-1070
# - NVIDIA-GeForce-GTX-1080
# - Quadro-M4000
# - NVIDIA-A100-PCIE-40GB-MIG-2g.10gb
# - NVIDIA-GeForce-GTX-1080-Ti
# - NVIDIA-GeForce-RTX-2080-Ti
# - NVIDIA-TITAN-Xp
# - Tesla-T4
# - NVIDIA-GeForce-RTX-3090
# - NVIDIA-TITAN-RTX
# - NVIDIA-RTX-A5000
# - Quadro-RTX-6000
# - Tesla-V100-SXM2-32GB
# - NVIDIA-A40
# - NVIDIA-RTX-A6000
# - Quadro-RTX-8000