apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cfl-dataset-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  storageClassName: rook-cephfs
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cfl-result-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 40Gi
  storageClassName: rook-cephfs
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cfl-pretrain-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: rook-cephfs
